### ISSUE TITLE
How to run with a specific version of python?

### ISSUE THREAD

**Issue by d0u9** [bfredl/nvim-ipy#11]
My neovim uses python2.7 as its default python runtime environment.

But I want `nvim-ipy` to run with another version python, for example python 2.6. Because some of my works can only works under python 2.6...

So, How to open a nvim-ipy window with a specific version of python?

**Comment by bfredl** [comment]
You need to ensure a kernel is registrerad for that python version, I would guess "python2.6 -M IPython kernel install" does the trick. And then ":IPython --kernel python2.6" I am traveling now but I wiłl check the details on saturday.

**Comment by d0u9** [comment]
I encountered another situation that I have two versions python installed, one is OSX's default and another is installed via homebrew. I want to run with the homebrew installed version which locates at `/usr/local/bin/python`. However, the neovim's python runtime environment is `/usr/bin/python`, the default one. So, how could I designated the former to run?

**Comment by bfredl** [comment]
Something like "/usr/local/bin/python -M IPython kernel install" ( or was it lowercase -m ?) but not sure what the kernel name would be then. I will test when i get home.

**Comment by d0u9** [comment]
Thx for your response.

**Comment by bfredl** [comment]
I just tested this, and it seems if you have more than one python2 and one python3 kernel you need to name them manually. This seems to work:
`/path/to/python -m IPython kernel install --name somekernelname --user`
and then you should be able to start it with `:IPython --kernel somekernelname` (substitute `somekernelname` as preferred)

**Comment by d0u9** [comment]
it works, thank you very much!

**Comment by bfredl** [comment]
nice, I will update the documentation.

**Comment by etheleon** [comment]
if you're using conda envs

you could just run `ipython kernel` it'll require you to install `ipykernel` first
