### ISSUE TITLE
Unknown function IPyConnect

### ISSUE THREAD

**Issue by languitar** [bfredl/nvim-ipy#12]
Executing `:IPython` just results in `Unknown function IPyConnect` and nothing else happens. On a recent master version of nvim.

**Comment by chriswl** [comment]
Issue #2 might help.

**Comment by languitar** [comment]
I am running this with anaconda python and the `PATH` set appropriately. pyzmq is installed in the conda environment. I can also execute the python plugin inside the conda python executable without errors. Is neovim ignoring the custom python interpreter?

Apart from that: please document the python requirements in the README file.

**Comment by languitar** [comment]
Ok, `:UpdateRemotePlugins` solved the issue. Why is this necessary?

**Comment by chriswl** [comment]
There is some explanation in the neovim documentation [here](https://neovim.io/doc/user/remote_plugin.html).

**Comment by bfredl** [comment]
It is a present limitation in nvim we would like to get rid of. Either `nvim` should compare all plugin files with a timestamp and update as neccesary, or plugin managers need to become neovim aware and in whatever `Install`/`Update` command do
```
if has("nvim")
    UpdateRemotePlugins
end if
```
