### ISSUE TITLE
Regression. E475: Invalid Argument, Channel doesn't exist

### ISSUE THREAD

**Issue by Palpatineli** [bfredl/nvim-ipy#15]
Hi bfredl,

Thanks for this wonderful plugin! After the last upgrade (where you defaulted to python3) I start to get this error e475 whenever I use IPy-Run or call IPyRun manual. My neovim is 0.1.3-dev. Even after I delete all other plugins and delete .vimrc this problem persists. Can you look into this please?

**Comment by bfredl** [comment]
Does `:python3 print("test")` work? Make sure you have the latest version of `python-client` installed for python3 (`pip3 install neovim --upgrade`).

**Comment by Palpatineli** [comment]
Thanks for the quick resposne! python-client upgrade did solve the problem. Didn't occur to me that the problem might be on the neovim side. I'm sorry. Please close.

**Comment by bfredl** [comment]
No problem!
