### ISSUE TITLE
E117: Unknown function: IPyConnect

### ISSUE THREAD

**Issue by dpavlic** [bfredl/nvim-ipy#2]
This looks like an interesting project; however, I can't get it off the ground. I insall the plugin via BundleInstall, start neovim, and attempt :IPython but I get:

```
E117: Unknown function: IPyConnect
```

I've just started using Neovim from Vim, so I may be missing something obvious.

**Comment by justmytwospence** [comment]
I can run the script itself (ie, `python .vim/plugins/nvim-ipy/rplugin/python/nvim_ipy.py`), but I still get this error in neovim.

**Comment by bfredl** [comment]
@justmytwospence Have you tried `:UpdateRemotePlugins` and restart nvim? If it doesn't help, what is the contents of `.nvim/.nvimrc-rplugin~` ?

**Comment by rsdenijs** [comment]
@bfredl. UpdateRemotePlugins solved it for me.

**Comment by larsks** [comment]
I'm seeing the same error:

    E117: Unknown function: IPyConnect

Running `:UpdateRemotePlugins` produces as output:

    remote/host: python host registered plugins ['nvim_ipy.py']
    remote/host: generated the manifest file in "/home/lars/.config/nvim/.init.vim-rplugin~"

...but has no effect on the error message.  The contents of `.init.vim-rplugin~` are:

    " python3 plugins


    " python plugins
    call remote#host#RegisterPlugin('python', '/home/lars/.config/nvim/bundles/nvim-ipy/rplugin/python/nvim_ipy.py', [
          \ {'sync': 0, 'name': 'IPyComplete', 'type': 'function', 'opts': {}},
          \ {'sync': 1, 'name': 'IPyConnect', 'type': 'function', 'opts': {}},
          \ {'sync': 0, 'name': 'IPyInterrupt', 'type': 'function', 'opts': {}},
          \ {'sync': 0, 'name': 'IPyObjInfo', 'type': 'function', 'opts': {}},
          \ {'sync': 1, 'name': 'IPyOmniFunc', 'type': 'function', 'opts': {}},
          \ {'sync': 0, 'name': 'IPyRun', 'type': 'function', 'opts': {}},
          \ {'sync': 0, 'name': 'IPyTerminate', 'type': 'function', 'opts': {}},
         \ ])

Running the `.py` file directly produces no errors:

    $ python ./rplugin/python/nvim_ipy.py
    $

Any suggestions as to what I should look at next? Thanks!
