### ISSUE TITLE
'IPythonPlugin' object has no attribute 'kc'

### ISSUE THREAD

**Issue by d0u9** [bfredl/nvim-ipy#20]
When I try to auto-complete, I get the error 'AttributeError: 'IPythonPlugin' object has no attribute 'kc''

```
error caught in async handler '/Users/sky/.dot/nvim/plugged/nvim-ipy/rplugin/python3/nvim_ipy:function:IPyComplete [[]]':
AttributeError("'IPythonPlugin' object has no attribute 'kc'",)
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.5.1/lib/python3.5/site-packages/neovim/plugin/host.py", line 91, in _on_notification
    handler(*args)
  File "/usr/local/opt/pyenv/versions/3.5.1/lib/python3.5/site-packages/neovim/plugin/host.py", line 160, in decoder
    return fn(*walk(decode_if_bytes, args, decode))
  File "/Users/sky/.dot/nvim/plugged/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 290, in ipy_complete
    reply = self.waitfor(self.kc.complete(line, pos))
AttributeError: 'IPythonPlugin' object has no attribute 'kc'
```

I use nvim-ipy in python3.5.11..

**Comment by doubleloop** [comment]
same here, Python 3.5.2rc1

**Comment by Unode** [comment]
I was also getting the same error. Try closing nvim running `:IPython` and then hitting `F5`.

**Comment by bfredl** [comment]
Does this happen after `:IPython` ? Note you need to wait for the kernel to start and connect (0.5-2 seconds) , only after the banner gets displayed with the language and version is the kernel ready to take commands.

**Comment by Unode** [comment]
I get it if I start nvim while editing a Python file and immediately press `F5`. If I run `:IPython` first I don't see the error.

**Comment by doubleloop** [comment]
@Unode, thanks that worked for me! 
One thing I have to figure out is how to run IPython2 (IPython works), i get `NoSuchKernel('python2',)` error..
