### ISSUE TITLE
IPython2 connect unsuccessful

### ISSUE THREAD

**Issue by Ron89** [bfredl/nvim-ipy#21]
In my impression, it used to work. But on latest update, the plugin failed to connect to IPython2. And by failed to connect, I mean, the iPython buffer is empty and whenever I try to send a line to it, it prompt me `kernel died`. Connection to IPython3 on the other hand, still works fine.

I am using `ipykernel-4.3.1` for python2.

**Comment by bfredl** [comment]
Does `jupyter console --kernel python2` work? If not you might to use `ipython2 kernelspec install-self --user` or if the kernel name is different, you need to specify it using `:IPython --kernel thename`

**Comment by Ron89** [comment]
Thanks. It is indeed the problem~
