### ISSUE TITLE
Difficulty restarting the kernel

### ISSUE THREAD

**Issue by damca** [bfredl/nvim-ipy#25]
I run `:call IPyTerminate()` which seems to successfully shut down the kernel. Subsequently running `:IPython` does instantiate a new process (as seen from Activity Monitor), but there is no connection with the buffer and sending commands to the new kernel doesn't work.

I've tried wiping/closing the IPython buffer after termination and before reinitialization, but to no avail. How else might I be able to conveniently restart the IPython kernel without closing Neovim?

Thanks for any reply! Stoked on this plugin otherwise!

Edit: It seems to restart fine about 70% of the time. Perhaps it is 'luckily' finding the right kernelspec? Forgive my naïveté.

**Comment by bfredl** [comment]
Running `:IPython` again shouldn't be necessary. On the next Run command sent, it will ask if the kernel should be restarted. After that, you will need to wait a second or two and then send that command again.

**Comment by damca** [comment]
Indeed that fixed it. Waiting a few seconds after answering 'yes' to the restart prompt allows the Jupyter kernel to connect with the buffer consistently.  Thanks for the prompt reply!
