### ISSUE TITLE
Connecting to new jupyter instance fails

### ISSUE THREAD

**Issue by Palpatineli** [bfredl/nvim-ipy#28]
After upgrading to jupyter 4.3.0, IPython calls fail to return any error message and opens an empty buffer. Any attempt execute python code in jupyter prompts the "Kernel died, Restart? [Y]es, [N]o" yet typing Y doesn't do anything.
nvim-ipy has been upgraded using Plug and UpdateRemotePlugin has been executed after the upgrade.

**Comment by bfredl** [comment]
Changes to connection logic was made. Please respond if this still is an issue.
