### ISSUE TITLE
neovim hangs while Scanning: [jupyter]

### ISSUE THREAD

**Issue by JohnReid** [bfredl/nvim-ipy#29]
Occasionally I see the message `[Scanning] jupyter` appear in the bottom left of neovim. Whilst this is going on, neovim hangs. I cannot edit my code. I assume this is something to do with `nvim-ipy` but I'm not sure. Does anyone know what's going on? I'm on the latest `nvim-ipy` github version (commit ad4007f19a377a74b57a673834b417ccedc58a1f).

**Comment by bfredl** [comment]
It is not a behavior initiated by this plugin. It could refer to scanning of helptags. What is your plugin manager?

**Comment by JohnReid** [comment]
Sorry for the noise. I used `vim-plug` for plugins.

**Comment by bfredl** [comment]
hmm, can't find it in vim-plug. nvim has a "Scanning: %s" message related to completion but that was not precisely what you saw either... You could grep for "Scanning" in your `vim/bundle/` directory.

**Comment by JohnReid** [comment]
My bad, it is actually reporting `Scanning: [jupyter]` not `[Scanning]: jupyter` which I first reported. This looks like a match to some autocomplete code in neovim relating to the jupyter window. I'm still not sure how to work around this. I guess the first step would be to turn autocomplete off.

**Comment by bfredl** [comment]
Moved to neovim/neovim#6390
