### ISSUE TITLE
E117: Unknown function: IPyConnect 

### ISSUE THREAD

**Issue by lucasfariaslf** [bfredl/nvim-ipy#31]
I'm both new to github and the vim word - by which I mean neovim. I saw there was a closed issue on this error  , #2  but I was unsure when whether to comment on it or create another issue. As the problem seems to be caused by something else, I decide to open a new issue. Sorry if that's the wrong reasoning.

The error happens when I try `:IPython`.  I ran `:UpdateRemotePlugins` as indicated in the mentioned issue and the output was:

`Encountered ImportError loading plugin at /home/lucasfariaslf/.vim/plugged/nvim-ipy/rplugin/python3/nvim_ipy: No module named 'jupyter_client'
Traceback (most recent call last):
  File "/home/lucasfariaslf/.local/lib/python3.5/site-packages/neovim/plugin/host.py", line 131, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
ImportError: No module named 'jupyter_client'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/lucasfariaslf/.local/share/nvim/rplugin.vim
`

I tried `IPython2` and got the same error, `ipython2 kernelspec install-self --user` didn't help either. 

It seems obvious that the problem might be cause by the lack of this `jupyter_client`, but I have no idea how to get it to work, as I googled and it's not something I could solve with a `pip install`.

**Comment by bfredl** [comment]
Install jupyter through your system package manager or `pip3 install jupyter`. Add `--user` if you install as non-root user.

**Comment by lucasfariaslf** [comment]
As I suspected, just a simple error... but sometimes you're just too fed up to try and spend more 2 hours trying to figure it out alone.

Thank you a lot, @bfredl. I'll close the issue.
