### ISSUE TITLE
Suggestion - default map vip<F5>

### ISSUE THREAD

**Issue by robertocarta** [bfredl/nvim-ipy#32]
I'm not sure this is the right place to write this, but I noticed that once you map a key to vip<F5> you've basically got yourself a vim implementation of jupyter notebooks. I think this should be included in the default keybinding and mentioned in the readme.

**Comment by bfredl** [comment]
Jupyter notebook is much more: markdown, multimedia etc. Rather than paragraphs some kind of cell functionality might be worth adding
