### ISSUE TITLE
cannot connect to a different kernel after terminate the present one

### ISSUE THREAD

**Issue by liushapku** [bfredl/nvim-ipy#33]
I created a kernel using `:IPython` and ran some code in it.
Then I quite the kernel by calling `IPyTerminate`

Then I tried to run some new code and got the prompt saying "kernal died" and ask me whether to restart the kernel.

If I choose to restart, then the kernel accepts new command.
If I choose not to restart, and using `:IPython` again trying to create a new kernel or using `:IPython --existing xxx.json` trying to connect to another existing kernel, nothing happened. No output buffer was created again and no code was executed.

How to connect to a different kernel after quitting the previous one?

**Comment by bfredl** [comment]
It will require some refactoring like using proper MultiKernelManager instead of JupyterConsoleApp.

**Comment by bfredl** [comment]
Should work now.
