### ISSUE TITLE
Add newline to Output

### ISSUE THREAD

**Issue by gilgameshskytrooper** [bfredl/nvim-ipy#36]
I am using nvim-ipy primarily for data analysis, and I noticed that due to the way the output is displayed, the first row of data (the one in the same row as the `Out` key word) is always shifted too far right.

This makes looking at tables kind of a pain.

Hence, I propose that a newline is inserted in the Output line in order to fix this display annoyance.

**Comment by bfredl** [comment]
It seems you are right, `\n` should be prepended to multiline output, ref https://github.com/ipython/ipython/blob/37852861db436d432aebf28150c6ea000833dad1/IPython/core/displayhook.py#L178

**Comment by bfredl** [comment]
please try latest master.
