### ISSUE TITLE
Tips for getting this to work on Windows with VIM 7.4 and IPython 3?

### ISSUE THREAD

**Issue by reckoner** [bfredl/nvim-ipy#4]
Hi,

I realize that neovim does not have a stable Windows GUI build yet and I would really like to use this plugin. I did manage to get VIM 7.4 and Ivanov's original to work on Windows with IPython 2.x. I would at least like to get VIM 7.4 working with IPython 3.x. Are there sections of your code that I could study to understand the changes that you made just from the IPython version 2 to version 3 standpoint? In other words, is Ivanov's work upgradable from the pure VIM standpoint or does it only work with neovim. I understand that the IPython team made some changes to the internal messaging that ipy-vim relied upon. 

Thanks!

**Comment by bfredl** [comment]
See [this](https://github.com/bfredl/nvim-ipy/commit/33df8fda75da0a4cba2a6e637771788c51b6f7c3) commit for the relevant changes, which should be independent of the vim/neovim differences. (apart from the `ThreadedKernelClient` import which is neovim/async specific)
There is a PR at ivanov/vim-ipython#114 that perhaps does what you want for vim (I have not tried it, but it looks it makes the analogous chanes)

**Comment by bfredl** [comment]
Seems this was fixed in "upstream" vim-ipython now.
