### ISSUE TITLE
Multiple notebook open More of Q than issue

### ISSUE THREAD

**Issue by yelled1** [bfredl/nvim-ipy#41]
If I have multiple jupyter lab ipynb open, then seems like I goto the latest when I invoke
``` IPython --existing```
How do list & select a specific one?
Thanks,

**Comment by bfredl** [comment]
If the notebook is python, you can use `%connect_info` magic inside the notebook. Somewhere in there there will be a line like

    jupyter <app> --existing kernel-12345.json

pass the json name after `--existing` also to this plugin.

**Comment by yelled1** [comment]
Worked beautifully. Thank u,

**Comment by bfredl** [comment]
no problem!
