### ISSUE TITLE
Run command as vim operator

### ISSUE THREAD

**Issue by rattletat** [bfredl/nvim-ipy#43]
Hi,

is it possible to use the run command as a operator on text objects? Often I would like to run the inner paragraph for example or the same indent (with indent textobject plugin).
Also, when opening the ipython buffer, could you set syntax=python automatically?

Thanks a lot!

**Comment by mightymicha** [comment]
Implemented it in my fork https://github.com/mightymicha/nvim-ipy

**Comment by bfredl** [comment]
@mightymicha Nice! I might integrate the operatorfunc part, in the weekend or so.

**Comment by JohnReid** [comment]
@bfredl did you integrate the operatorfunc part? I would be keen on this. Am going to look at @rattletat 's fork

**Comment by JohnReid** [comment]
I cannot find the fork now: https://github.com/mightymicha/nvim-ipy 404 error :(

**Comment by rattletat** [comment]
@JohnReid Hi yes sorry, it seems I deleted it. However, I switched to another plugin which uses a more universal approach and which work quite well:
https://github.com/kassio/neoterm

**Comment by JohnReid** [comment]
Thx for the reply. I'll check it out. I do like nvim-ipy though.
