### ISSUE TITLE
Mapping happens anyway, causing collisions while mapping to F5

### ISSUE THREAD

**Issue by Soulthym** [bfredl/nvim-ipy#49]
I just started using the Plugin with NVim coupled with Vundle, and upon installing, the mappings get done even though I set `g:nvim_ipy_perform_mappings = 0` in my init.vim 
```vim
Plugin 'bfredl/nvim-ipy'
let g:nvim_ipy_perform_mappings = 0
```
then I reload my init.vim and still pressing F5 gives me this error:
```
error caught in async handler '/home/soulthym/.config/vim/bundle/nvim-ipy/rplugin/python3/nvim_ipy:function:IPyRun [['source ~/.config/vim/vimrc\n']]'            
Traceback (most recent call last):
  File "/home/soulthym/.config/vim/bundle/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 321, in ipy_run
    if self.km and not self.km.is_alive():
AttributeError: 'IPythonPlugin' object has no attribute 'km'
Press ENTER or type command to continue
```

1) Shouldn't $HOME/.config/nvim/init.vim be sourced?  
2) why is F5 still mapped after IPy-Run? It forces me to map another shortcut to use IPy-RunCell

**Comment by bfredl** [comment]
what does "reload" mean? you have to restart nvim, otherwise existing mappings will not be cleared out.

**Comment by Soulthym** [comment]
@bfredl I meant restarting nvim
But I just found the reason it was not working,
I had this:
```
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
```
in my `.vim/vimrc` , making it impossible to unload what had already been sourced.

I'll find another way to have persistent views.

**Comment by bfredl** [comment]
I guess you can `unmap` stuff to have them removed from your persisent view.

Not really an issue with this repo then.
