### ISSUE TITLE
nevim + python3

### ISSUE THREAD

**Issue by razvanc-r** [bfredl/nvim-ipy#5]
Is it possible to make this thing work with `neovim` that has only `python3`? I went in the `rplugins` directory and changed that to `python3` instad of `python`. But that didn't get me too far... I'm getting an error about some channel being closed... There's no option for me but to use `python3` on this particular machine... thanks

**Comment by bfredl** [comment]
Please try the `py3` branch of this repo (I will merge this into master soon), and do the same trick (move python to python3). 
(Eventually there should be some way to register a rplugin working with both python and python3)

**Comment by razvanc87** [comment]
not really... if you try to `UpdatePluginRegistry` or whatever that command is called, but it gives an error when you don't have `python` available (which I don't) and try to register a plugin with that works with `python`... which makes sense :), but I'll try the `py3` branch and let you know, thanks!

**Comment by razvanc87** [comment]
yep, it works (after moving `rplugin/python` to `rplugin/python3` prior to running `UpdateRemotePlugins`, thanks

**Comment by bfredl** [comment]
python 3 is default now :)
