### ISSUE TITLE
no request handler registered after installing with vim-plug

### ISSUE THREAD

**Issue by Soulthym** [bfredl/nvim-ipy#52]
After switching from Vundle to vim-plug, re-installing all my plugins without any error, I get the following error when I try to start a kernel: 
```
Error detected while processing function IPyConnect[1]..remote#define#request:                                                                                      
line    2:
Error invoking '/home/soulthym/.config/vim/bundle/nvim-ipy/rplugin/python3/nvim_ipy:function:IPyConnect' on channel 82 (python3-rplugin-host):
no request handler registered for "/home/soulthym/.config/vim/bundle/nvim-ipy/rplugin/python3/nvim_ipy:function:IPyConnect"
```
Any idea of what's going wrong? I couldn't find a solution in past issues

**Comment by bfredl** [comment]
Did you run `UpdateRemotePlugins` after re-installing?

**Comment by Soulthym** [comment]
I actually forgot to do that, it totally fixed it!

Thanks, I added it to my update script
