### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by razvanc87** [bfredl/nvim-ipy#6]
So I see you're not really maintaining this repository all that much, but I think that there is some interest in it (by the average neovim user).  I would like to propose a collaboration for developing a flexible plugin that will work with jupyter. I didn't quite like how things looked in your plugin, or `vim-ipython` for that matter. It looks like a big mess and I think we can do better. Documentation is sparse, but I already made quite some progress in discovering how things work and should be used I think. Your plugin and `vim-ipython` is the start of [nvim-jupyter](https://github.com/razvanc87/nvim-jupyter). Let me know what you think.

PS. at the moment the plugin is not functional (I'm waiting for a response to my [issue about using the @proerpty decorator](https://github.com/neovim/python-client/issues/126)), I just started writing it yesterday and it was pretty difficult finding out how things work but I think I am getting the hang of it.

**Comment by bfredl** [comment]
Depends what you mean with maintaining. I have mostly not added more features, simply because it does all what I want it to do. (except from adding python3 support just last week). PRs and feature requests are of course welcome. But yes I should do some more work on the documentation.

> it looks like a big mess and I think we can do better.

What is it specifically you think we should do better, I mean in the basic design? Note that sending code already is a generic `IPyRun("code...")` function which can be used flexibly, for instance I have some bindings in my `nvimrc` for save+reload. I know the async event handling is a bit of a mess. `@ipy_async` could just be eliminated, as `python-client` already does this for us, but otherwise I don't really know how to make it simpler (we're handling async events from two sources).

I thought of swithing to `nvim-jupyter` name when adapting to `Jupyter/IPython 4.0` as it will clearly separate what is Jupyter from IPython. I will look more  into your repo later today.

**Comment by razvanc87** [comment]
Well, I'm at the very beginning now (just started yesterday) and am slowly moving cause I don't have enough experience with `vim` scripting, nor `jupyter` for that matter. I have quite some few features in mind (for which I need help, cause I'm totally new at this remote messaging stuff) other than refactoring and cleaning up the code base. A few things include:

- automatic connection to remote host through ssh given the connection file (path or the random hash)
- figure out a way to integrate pictures (as in `%matplotlib inline`)
- _connect to the notebook and make it execute commands on the kernel_ (don't know if this is possible but would be super useful). Example: I do some work in `neovim`, send commands to be executed on the kernel, then have the `notebook` plot me the results (after using `%matplotlib inline`). This is directly related to the previous feature, but could probably be extended to all sorts of crazy things

And finally, a big thing for me is having a clean code so that it's easy to understand, have proper documentation and give others the possibility to easily extend the plugin. For example, in my version, I defined the `JExecute` command which accepts the range object from `neovim`, this is a very clean way to execute the visually selected lines (but does this work with `neovim` key mapping? I don't know, not experienced enough, but I would hope so...). In essence there aren't that many things, but I would definitely like to explore the possibilities.

**Comment by bfredl** [comment]
If you haven't seen it already, look at the [messaging documentation](http://ipython.org/ipython-doc/dev/development/messaging.html) (it was a life-saver for me when implementing this repo).

It should work, but ranges only support linewise selection. `get_visual_selection()` also support charwise selection, to evaluate an expression in the middle of a line. ( I like to think of it as a missing builtin function) `IPyRun(<SID>get_visual_selection())` is also both race-free _and_ asynchronous. To add more extensibility, I could think of `IPyRun(code, callback)` to enable further processing of the result in a callback function. 

> automatic connection to remote host through ssh given the connection file (path or the random hash)

Does `ipython console` support that, then nvim-ipy should also, I will look into it.

> figure out a way to integrate pictures (as in %matplotlib inline)

I also thought about this. Soon, neovim will support a more flexible windowing model, which should allow a GUI with a picture window, or something.

> connect to the notebook and make it execute commands on the kernel

This was discussed in IPython for IPython 3 notebook (it is a  popular request) but I don't know how far along it is. Also interesting would be "deep" integration where neovim could be used to edit cells in a running notebook (I think ipython-emacs bridge does this).

**Comment by razvanc87** [comment]
Yes... I know about that messaging documentation. It was helpful (slightly :D). Anyway, maybe keep on following my progress on this and if you're interested at some point let me know.

**Comment by razvanc87** [comment]
By the way, [this is how](https://github.com/razvanc87/nvim-jupyter/blob/master/rplugin/python3/nvim_jupyter/__init__.py#L105) I tackle the visual (block) selection issue (without any further `vim` functions / commands).

**Comment by bfredl** [comment]
Regarding ssh,  I just tested `nvim-ipy` can already connect using `--ssh localhost` as with `ipython console` (no password prompt, but can use pubkey or a shared connection for now), but then I get signature mismatches on requests, so will need some futher digging.
