### ISSUE TITLE
Add support for jupyter

### ISSUE THREAD

**Issue by jorgesca** [bfredl/nvim-ipy#7]
Hi,
After updating to jupyter I realized that this plugin doesn't work anymore. Is this on the TODO list?

**Comment by bfredl** [comment]
I did try to update for Jupyter 4.0 and it seems to work for me. If you just run the plugin module in the interpreter, like
`python rplugin/python/nvim_ipy.py`
do you get any import error? (make sure to use the same python version as you run this plugin with, python2 per default)

**Comment by jorgesca** [comment]
I am closing this issue as it seems the problem was due to mixed python versions. I am running jupyter within a conda environment but I had installed neovim's python client using my distro package manager. Once I realized that (unfortunately it took a long time), I fixed the issue by installing neovim's python client from within the conda env (and thus eliminating the use of different python versions)
I apologize for not reporting this before, once I was able to get this plugin working I jumped into working and forgot about the issue.
